# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Hacklytics2024',
                'doc_host': 'https://Xiaotong1120.github.io',
                'git_url': 'https://github.com/Xiaotong1120/Hacklytics2024',
                'lib_path': 'Hacklytics2024'},
  'syms': { 'Hacklytics2024.Handwriting_recognition': {},
            'Hacklytics2024.Output_Generation': {},
            'Hacklytics2024.core': {'Hacklytics2024.core.foo': ('output_generation.html#foo', 'Hacklytics2024/core.py')}}}
